import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { LockKeyhole, Mail, ShieldCheck } from "lucide-react";
import { useState } from "react";
export function AuthScreen({ mode, busy, error, onModeChange, onSubmit }) {
    const [email, setEmail] = useState("");
    const [password, setPassword] = useState("");
    return (_jsx("div", { className: "min-h-screen px-4 py-8 text-slate-100", children: _jsxs("div", { className: "mx-auto flex min-h-[calc(100vh-4rem)] max-w-6xl items-stretch overflow-hidden rounded-[2rem] border border-white/10 bg-slate-950/80 shadow-panel", children: [_jsxs("section", { className: "hidden w-[44%] flex-col justify-between bg-slate-900/90 p-10 lg:flex", children: [_jsxs("div", { className: "space-y-10", children: [_jsxs("div", { className: "inline-flex items-center gap-3 rounded-full border border-sky-400/20 bg-sky-400/10 px-4 py-2 text-sm font-medium text-sky-200", children: [_jsx(ShieldCheck, { className: "size-4" }), "PM2 Log Viewer"] }), _jsxs("div", { className: "space-y-5", children: [_jsx("h1", { className: "max-w-md text-4xl font-semibold leading-tight text-white", children: "A calm control room for remote PM2 hosts, processes, and live logs." }), _jsx("p", { className: "max-w-md text-base leading-7 text-slate-400", children: "Connect over SSH, pin host fingerprints, inspect PM2 process health, and stream logs in real time without leaving the browser." })] })] }), _jsxs("div", { className: "grid gap-4 text-sm text-slate-300", children: [_jsx("div", { className: "rounded-3xl border border-white/10 bg-white/5 p-5", children: "Encrypted SSH secrets at rest with AES-256-GCM and a per-deployment master key." }), _jsx("div", { className: "rounded-3xl border border-white/10 bg-white/5 p-5", children: "Socket-backed log streaming with pause, regex filters, download, and bounded memory." })] })] }), _jsx("section", { className: "flex flex-1 items-center justify-center px-6 py-10 sm:px-10", children: _jsxs("div", { className: "w-full max-w-md space-y-8", children: [_jsxs("div", { className: "space-y-3", children: [_jsxs("div", { className: "inline-flex rounded-full border border-white/10 bg-white/5 p-1", children: [_jsx("button", { className: `rounded-full px-4 py-2 text-sm transition ${mode === "login" ? "bg-white text-slate-950" : "text-slate-300"}`, onClick: () => onModeChange("login"), type: "button", children: "Sign in" }), _jsx("button", { className: `rounded-full px-4 py-2 text-sm transition ${mode === "register" ? "bg-white text-slate-950" : "text-slate-300"}`, onClick: () => onModeChange("register"), type: "button", children: "Create account" })] }), _jsxs("div", { children: [_jsx("h2", { className: "text-3xl font-semibold text-white", children: mode === "login" ? "Welcome back" : "Create your operator account" }), _jsx("p", { className: "mt-2 text-sm leading-6 text-slate-400", children: mode === "login"
                                                    ? "Use your email and password to return to your PM2 workspace."
                                                    : "Start with a private workspace for your hosts, tags, and audit trail." })] })] }), _jsxs("form", { className: "panel space-y-5 p-6", onSubmit: async (event) => {
                                    event.preventDefault();
                                    await onSubmit(mode, email, password);
                                }, children: [_jsxs("label", { className: "block space-y-2 text-sm text-slate-300", children: [_jsxs("span", { className: "flex items-center gap-2", children: [_jsx(Mail, { className: "size-4 text-slate-500" }), "Email"] }), _jsx("input", { className: "field", onChange: (event) => setEmail(event.target.value), placeholder: "you@example.com", type: "email", value: email })] }), _jsxs("label", { className: "block space-y-2 text-sm text-slate-300", children: [_jsxs("span", { className: "flex items-center gap-2", children: [_jsx(LockKeyhole, { className: "size-4 text-slate-500" }), "Password"] }), _jsx("input", { className: "field", minLength: 8, onChange: (event) => setPassword(event.target.value), placeholder: "At least 8 characters", type: "password", value: password })] }), error ? (_jsx("div", { className: "rounded-2xl border border-rose-400/20 bg-rose-400/10 px-4 py-3 text-sm text-rose-200", children: error })) : null, _jsx("button", { className: "button-primary w-full", disabled: busy, type: "submit", children: busy ? "Working..." : mode === "login" ? "Sign in" : "Create account" })] })] }) })] }) }));
}
